/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7924fa9688b195e8b9193dfb0a9d75d5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		APP_DB: D1Database;
		VECTORIZE: VectorizeIndex;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
